name: 01 - Configure

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'docker image and tag'
        default: 'maverick1542/web:latest'
        
jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ORG_TOKEN }} ### need a PAT that has repo access to write bnack the compose file
      - name: Get repository name
        id: repo-name
        uses: MariachiBear/get-repo-name-action@v1.1.0
        with:
          with-owner: 'false'
          string-case: 'lowercase'
      - name: create docker-compose
        run: | 
          sed -i 's/REPO_NAME/${{ steps.repo-name.outputs.repository-name }}/g' deploy/docker-compose.yml
          sed -i 's/DOCKER_IMAGE/${{ inputs.image }}/g' deploy/docker-compose*
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated compose files
          push_options: '--force'
          branch: main
